name: custom-atomic-os
description: My custom atomic Linux distribution powered by BlueBuild
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    install:
      - zsh
      - neofetch
      - htop
      - git
      - curl
      - tmux
      - distrobox

  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.mattjakeman.ExtensionManager
        - org.mozilla.firefox
        - io.github.celluloid_player.Celluloid
    repo-name: flathub
    repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo

  - type: systemd
    system:
      enabled:
        - sshd
        - podman.socket

